version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app-hp && npm run dev"
    ports:
      - "3000:3000"